generator: admingenerator.generator.doctrine
params:
    model: Parabol\AdminCoreBundle\Entity\Gallery
    namespace_prefix: Parabol
    concurrency_lock: ~
    bundle_name: AdminCoreBundle
    pk_requirement: ~
    i18n_catalog: Admingenerator
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List of Galleries
            display: [name, type, isEnabled]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New Gallery
            display: [isEnabled, type, files, translations]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "Editing the gallery: \"%object%\"|{ %object%: Gallery.name }|"
            display: [isEnabled, type, files, translations]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "Viewing the gallery: \"%object%\"|{ %object%: Gallery.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
