generator: admingenerator.generator.doctrine
params:
    model: Parabol\AdminCoreBundle\Entity\MenuItem
    namespace_prefix: Parabol
    concurrency_lock: ~
    bundle_name: AdminCoreBundle
    pk_requirement: ~
    i18n_catalog: Admingenerator
    fields: 
        menu:
          addFormOptions:
              attr:
                required: true
        type:
          addFormOptions:
              choices: [list]
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    filters:
        params:
            display: [type, displayOnUrl]
    list:
        params:
            title: List for AdminCoreBundle
            display: [name, url, parent, isEnabled, displayOnUrl, type, sort]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New object for AdminCoreBundle
            display: [isEnabled, menu, parent, name, url, type, lead, displayOnUrl]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: MenuItem.name }|"
            display: [isEnabled, menu, parent, name, url, type, lead, displayOnUrl]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: MenuItem.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
