generator: admingenerator.generator.doctrine
params:
    model: Parabol\AdminCoreBundle\Entity\TextBlock
    namespace_prefix: Parabol
    concurrency_lock: ~
    bundle_name: AdminCoreBundle
    pk_requirement: ~
    i18n_catalog: Admingenerator
    fields: 
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List of Text Blocks
            display: [name, isEnabled, sort]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New Block of Text
            display: [isEnabled, type, translations]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: TextBlock.name }|"
            display: [isEnabled, type, translations]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: TextBlock.name }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
