<?php

namespace Parabol\AdminCoreBundle\Repository;

/**
 * GalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GalleryRepository extends \Parabol\BaseBundle\Entity\Base\BaseRepository
{
	
	use \Parabol\DoctrineBehaviorsBundle\Sortable\Entity\SortableRepository;

	public function allEnabledByType($type)
	{
		
		$alias = $this->getAlias();

		$qb = $this->createQueryBuilder($alias)
			->leftJoin($alias.'.files', 'f')
			->where($alias.'.isEnabled = 1')
			->andWhere($alias.".type IN ('".implode('","', (array)$type)."')");
		

		return $qb;
	}

	public function findAllEnabledLogotypes()
	{
		return $this->allEnabledByType('logotypes')->getQuery()->getResult();
	}

	public function findAllEnabledByType($type)
	{
		return $this->allEnabledByType($type)->getQuery()->getResult();
	}
}
