<?php

namespace Parabol\AdminCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemRepository extends \Parabol\BaseBundle\Entity\Base\BaseRepository
{
	use \Parabol\DoctrineBehaviorsBundle\Sortable\Entity\SortableRepository;


	protected function addSortingScope(\Doctrine\ORM\QueryBuilder $qb, $entity)
    {
    	$qb->andWhere('e.menu = :menu')
    		->setParameter(':menu', $entity->getMenu()->getId())
    	   ->andWhere('e.type = :type')
    		->setParameter(':type', $entity->getType());

    	if($entity->getDisplayOnUrl()) $qb->andWhere('e.displayOnUrl = :displayOnUrl')->setParameter(':displayOnUrl', $entity->getDisplayOnUrl());
    	else $qb->andWhere('e.displayOnUrl IS NULL');

    	if($entity->getParent()) $qb->andWhere('e.parent = :parent')->setParameter(':parent', $entity->getParent()->getId());
    	else $qb->andWhere('e.parent IS NULL');
    }

    public function findParents()
    {
        return $this->createQueryBuilder('mi')
                    ->where('mi.parent IS NULL')
                    ;
    }
}
