<?php

namespace Parabol\AdminCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends \Parabol\BaseBundle\Entity\Base\BaseRepository
{
	use \Parabol\DoctrineBehaviorsBundle\Sortable\Entity\SortableRepository;

	public function findOneBySlug($slug)
	{
		return $this->createQueryBuilder('p')
					->innerJoin('p.translations', 'pt')
					->where('pt.slug = :slug')
					->setParameter(':slug', $slug)
					->setMaxResults(1)
					->getQuery()
					->getOneOrNullResult();
	}

	public function sortOrder()
    {
        return 'desc';
    }    
	
}
