<?php

namespace Parabol\AdminCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoRepository extends EntityRepository
{
}
