services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.pcre:
        class: Jasny\Twig\PcreExtension
        tags:
          - { name: twig.extension }