<?php

namespace App\AdminCoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TextBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextBlockRepository extends \Parabol\AdminCoreBundle\Repository\TextBlockRepository
{
	
}
