generator: admingenerator.generator.doctrine
params:
    model: App\AdminCoreBundle\Entity\Seo
    namespace_prefix: App
    concurrency_lock: ~
    bundle_name: AdminCoreBundle
    pk_requirement: ~
    i18n_catalog: Admingenerator
    fields: 
        redirectStatusCode:
            formType: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            formOptions:
                choices: 
                    301: 301 Moved Permanently
                    302: 302 Found
                    307: 307 Temporary Redirect
                    308: 308 Permanent Redirect
                    404: 404 Not Found
                required: false 
        robots:
            formType: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            formOptions:
                choices: 
                    index: index
                    noindex: noindex
                    follow: follow
                    nofollow: nofollow
                    none: none
                    noarchive: noarchive
                    nosnippet: nosnippet
                    noodp: noodp
                required: false
                multiple: true
                expanded: true
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title: List for AdminCoreBundle
            display: [url, inherited, redirectTo, redirectStatusCode, title, keywords, ogTitle, robots]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    excel:
        params: ~
        filename: ~
        filetype: ~
    new:
        params:
            title: New object for AdminCoreBundle
            display: 
                NONE: [url, inherited]
                Redirect: [redirectTo, redirectStatusCode]
                Tags: [title, description, keywords]
                OpenGraph: [ogTitle, ogDescription, ogImage]
                Robots: [robots]
            actions:
                save: ~
                list: ~
    edit:
        params:
            title: "You're editing the object \"%object%\"|{ %object%: Seo.title }|"
            display: [url, inherited, title, description, keywords, ogTitle, ogDescription, ogImage, robots]
            actions:
                save: ~
                list: ~
    show:
        params:
            title: "You're viewing the object \"%object%\"|{ %object%: Seo.title }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
